version: "3.2"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=parking_db
      - POSTGRES_USER=parking_user
      - POSTGRES_PASSWORD=parking_password
    ports:
      - 5432:5432
  parking-app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    container_name: parking-app
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/parking_db
      - POSTGRES_DB=parking_db
      - POSTGRES_USER=parking_user
      - POSTGRES_PASSWORD=parking_password
    depends_on:
      - db